- hosts: all
  become: true
  tasks:
      - name: add stuart
        user:
            name: stuart
            password: $6$YpZnGqOjqj5SY71O$aUgWMpNBsj/nKIVWA3lGJOZxhsuHAB2Oxo/Z2PK9Djkdtgsgv.pu5X4tIZewoaaRdN4s40.d1yTEBxVyf5rmg/
            group: wheel
            shell: /bin/zsh
      - name: ensure package lists are up-to-date
        pacman:
            update_cache: yes
      - name: ensure neovim is at the latest version
        pacman:
            name: neovim
            state: latest
      - name: ensure x2go is at the latest version
        pacman:
            name: x2goserver
            state: latest
      - name: create x2go db
        shell: x2godbadmin --createdb && touch /root/x2godbadmin
        args:
            creates: /root/x2godbadmin
      - name: install openbox
        pacman:
            name: openbox
            state: latest
      - name: install rxvt
        pacman:
            name: rxvt-unicode
            state: latest
      - name: install feh
        pacman:
            name: feh
            state: latest
      - name: create wallpaper directory
        file:
            path: /wallpaper
            state: directory
            mode: 0777
      - name: install wallpaper
        get_url:
            url: https://static.pexels.com/photos/132037/pexels-photo-132037.jpeg
            dest: /wallpaper/wallpaper.jpg
            mode: 0666
      - name: create openbox config directory
        file:
            path: /home/stuart/.config/openbox
            state: directory
            mode: 0755
            owner: stuart
      - name: upload openbox autostart file
        copy:
            src: autostart
            dest: /home/stuart/.config/openbox
            mode: 0700
            owner: stuart
      - name: create fonts directory
        file:
            path: /home/stuart/.fonts
            state: directory
            mode: 0755
            owner: stuart
      - name: upload menlo
        copy:
            src: Menlo-for-Powerline/Menlo for Powerline.ttf
            dest: /home/stuart/.fonts
            mode: 0600
            owner: stuart
      - name: update font cache
        shell: fc-cache -vf ~/.fonts && touch .donefonts
        args:
            creates: /root/.donefonts
        become_user: stuart
        become: true
      - name: upload Xresources
        copy:
            src: Xresources
            dest: /home/stuart/.Xresources
            mode: 0600
            owner: stuart
      - name: install zsh
        pacman:
            name: zsh
            state: latest
      - name: install git
        pacman:
            name: git
            state: latest
      - name: clone zsh antigen
        git:
            repo: https://github.com/zsh-users/antigen.git
            depth: 1
            dest: /home/stuart/antigen
        become: true
        become_user: stuart
      - name: upload zshrc
        copy:
            src: zshrc
            dest: /home/stuart/.zshrc
            mode: 0600
            owner: stuart
      - name: install python3
        pacman:
            name: python
            state: latest
      - name: install pip
        pacman:
            name: python-pip
            state: latest
      - name: install python neovim
        pip:
            name: neovim
            state: latest
      - name: install dein for nvim
        shell: curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh && sh ./installer.sh ~/.vim/bundles
        args:
            creates: .vim/bundles/repos/github.com/Shougo/dein.vim/README.md
        become: true
        become_user: stuart
      - name: create nvim config directory
        file:
            path: /home/stuart/.config/nvim
            state: directory
            mode: 0755
            owner: stuart
      - name: upload init.vim
        copy:
            src: init.vim
            dest: /home/stuart/.config/nvim/init.vim
            mode: 0600
            owner: stuart
      - name: install nvim plugins
        shell: nvim -c "call dein#install()" -c "q" --headless
        become: true
        become_user: stuart
